workspace = { members = ["sh-macro"] }
[package]
name = "sh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sh-macro = { path = "./sh-macro" }
